
general:
  save_dir: "./pretrained_models_local/"
  device: "cuda"
  seed: 42
  num_workers: 0
  log_dir: "CVAE_logs"
  progress_bar: True
  n_samples_each_class: 4
  max_images: 8
  callback_every: 1
dataset:
  dataset: "cifar10"
  mnist_digits: null
classifier:
  classifier: "cifar10_cnn"
  model_name: "all"
  epochs: 20
  batch_size: 64
  lr: 0.1
  momentum: 0.5
  optimizer: "SGD"
  no_print: True
vae:
  vae_model: "cifar10_cvae_captain"
  model_name: "all"
  use_causal: False
  n_alpha: 1
  n_beta: 63
  alpha_samples: 25
  beta_samples: 25
  lam_ml: 1
  batch_size: 32
  lr: 0.001
  b1: 0.9
  b2: 0.999
  weight_decay: 0
  optimizer: "Adam"
  image_size: 32
  epochs: 1





