
general:
  save_dir: "./pretrained_models_local/"
  device: "cuda"
  seed: 42
  num_workers: 0
  log_dir: "CVAE_logs"
  progress_bar: True
  n_samples_each_class: 4
  max_images: 8
  callback_every: 1
  callback_digits: False
  sweeping_stepsize: 1
dataset:
  dataset: "cifar10"
  mnist_digits: null
classifier:
  classifier: "cifar10_cnn"  # "cifar10_cnn"  "vgg_11"
  model_name: "all"
  epochs: 20  # 20
  batch_size: 64
  lr: 0.001
  momentum: 0.5
  optimizer: "SGD"
  no_print: True  # True
vae:
  vae_model: "cifar10_cvae_own"
  model_name: "all"
  use_causal: True
  n_alpha: 1
  n_beta: 63
  alpha_samples: 100
  beta_samples: 25
  lam_ml: 0.5
  batch_size: 64
  lr: 0.0005  # 0.0005
  b1: 0.5
  b2: 0.999
  weight_decay: 0
  optimizer: "Adam"
  image_size: 32
  epochs: 1





