### Basic setup arguments
classifier: "mnist_cnn_overfit"  # choices: mnist_cnn, mnist_cnn_overfit, fmnist_cnn, cifar10_cnn
vae_model: "mnist_cvae"  # choices: mnist_cvae, fmnist_cvae, cifar10_cvae
dataset: "mnist_overfit"  # choices: mnist, mnist_overfit, fmnist, cifar10

mnist_digits: [3,8]  # choices: "None", "a,b,c,...,z" note that this basically determines which classes you want to include
device: "cuda"  # choices: cuda, cpu
save_dir: "./pretrained_models_local/"

### Basic optimization arguments
epochs: 50
batch_size: 64
lr: 0.1
momentum: 0.5
b1: 0.5
b2: 0.999
optimizer: "SGD" # choices: SGD, Adam

### CVAE-specific arguments
image_size: 32  # for mnist and fmnist pick 28, for cifar10 pick 32
n_alpha: 1
n_beta: 7
alpha_samples: 100
beta_samples: 25
lam_ml: 0.05
use_causal: True

### optional not used arguments
sampler: "default"
embed: False
dropout: False
freeze: []


