
general:
  save_dir: "./pretrained_models/"
  device: "cuda"
  seed: 42
  num_workers: 0
  log_dir: "CVAE_logs"
  progress_bar: True
  n_samples_each_class: 4
  max_images: null
  callback_every: 1
  callback_digits: False
  sweeping_stepsize: 1
  show_probs: False

dataset:
  dataset: "fmnist"
  include_classes: null

classifier:
  classifier: "fmnist_cnn"
  model_name: "fmnist_all"
  epochs: 20
  batch_size: 64
  lr: 0.1
  momentum: 0.5
  optimizer: "SGD"
  no_print: True

vae:
  vae_model: "fmnist_cvae"
  model_name: "fmnist_all"
  use_causal: True
  n_alpha: 1
  n_beta: 7
  alpha_samples: 100
  beta_samples: 25
  lam_ml: 0.05
  batch_size: 64
  lr: 0.0005
  b1: 0.5
  b2: 0.999
  weight_decay: 0
  optimizer: "Adam"
  image_size: 28
  epochs: 1





