general:
  save_dir: "./pretrained_models_local/"
  device: "cuda"
  seed: 42
  num_workers: 0
  log_dir: "CVAE_logs"
  progress_bar: True
  n_samples_each_class: 3
  callback_every: 1
  callback_digits: True

dataset:
  dataset: "fmnist"
  mnist_digits: [0, 3, 4]
classifier:
  classifier: "fmnist_cnn"
  model_name: "fmnist_model_034.pt"
  epochs: 50
  batch_size: 64
  lr: 0.1
  momentum: 0.5
  optimizer: "SGD"
  no_print: True
vae:
  vae_model: "fmnist_cvae"
  model_name: "fmnist_model_034.pt"
  use_causal: True
  n_alpha: 2
  n_beta: 4
  alpha_samples: 100
  beta_samples: 25
  lam_ml: 0.05
  batch_size: 32
  lr: 0.0001
  b1: 0.5
  b2: 0.999
  weight_decay: 0
  optimizer: "Adam"
  image_size: 28
  epochs: 30
  max_images: null
  sweeping_stepsize: 1





