
general:
  save_dir: "./pretrained_models_local/."
  device: "cuda"
dataset:
  dataset: "mnist"
  mnist_digits: [3,8]
classifier:
  classifier: "mnist_cnn"
  model_name: "model1"
  epochs: 1
  batch_size: 64
  lr: 0.1
  momentum: 0.5
  optimizer: "SGD"
vae:
  vae_model: "mnist_cvae"
  model_name: "model1"
  use_causal: True
  n_alpha: 1
  n_beta: 7
  alpha_samples: 100
  beta_samples: 25
  lam_ml: 1
  batch_size: 64
  lr: 0.0005
  b1: 0.5
  b2: 0.999
  weight_decay: 0
  optimizer: "Adam"
  image_size: 28
  epochs: 1





